# conf/cfdbench.yaml
root:
  datapipe:
    source:
      data_dir: "${ONESCIENCE_CFDBENCH_DATA_DIR}"
      data_name: "tube_prop_bc_geo"
    verbose: True

    data:
      task_type: "auto"
      norm_props: true
      norm_bc: true
      delta_time: 0.1
      stable_state_diff: 0.001
      split_ratios: [0.8, 0.1, 0.1]
      seed: 0
      num_rows: 64
      num_cols: 64

    dataloader:
      batch_size: 128
      eval_batch_size: 16
      num_workers: 4

  model:
    name: "fno"
    in_chan: 2
    out_chan: 2
    ffn_depth: 8
    ffn_width: 100
    autoffn_depth: 8
    autoffn_width: 200
    deeponet_width: 100
    branch_depth: 8
    trunk_depth: 8
    act_fn: "relu"
    act_scale_invariant: true
    act_on_output: false
    autoedeeponet_width: 100
    autoedeeponet_depth: 8
    autoedeeponet_act_fn: "relu"
    fno_depth: 4
    fno_hidden_dim: 32
    fno_modes_x: 12
    fno_modes_y: 12
    unet_dim: 12
    unet_insert_case_params_at: "input"
    resnet_depth: 4
    resnet_hidden_chan: 16
    resnet_kernel_size: 7
    resnet_padding: 3

  training:
    output_dir: "./result"
    mode: "train_test"
    num_epochs: 200
    lr: 1.0e-3
    lr_step_size: 20
    lr_gamma: 0.9
    log_interval: 100
    eval_interval: 20
    loss_name: "nmse"
    gpuid: 0
