fno_config:
  datapipe:
    source:
      data_dir: "${ONESCIENCE_DATASETS_DIR}/PDENNEval/data/" 
      file_name: "2D_DarcyFlow_beta0.1_Train.hdf5"
    verbose: True
    data:
      single_file: True
      reduced_resolution: 1
      reduced_resolution_t: 1
      reduced_batch: 1
      initial_step: 1
      pde_name: "2D_Darcy_Flow"

    dataloader:
      batch_size: 64
      num_workers: 4
      pin_memory: False

  model:
    name: "FNO"
    num_channels: 1
    modes: 12
    width: 20

  training:
    # output_dir 在这里！
    output_dir: "./checkpoint/" 
    if_training: True
    continue_training: False
    save_period: 20
    seed: 0
    training_type: "single"
    t_train: 2
    epochs: 10
    
    optimizer:
      name: 'Adam'
      lr: 1.0e-3
      weight_decay: 1.0e-4
    
    scheduler:
      name: "StepLR"
      step_size: 100
      gamma: 0.5