deeponet_config:
  datapipe:
    source:
      data_dir: "YOUR_DATASET_DIR_PATH"
      file_name: "1D_Cahn-Hilliard_10e-6_0.01.hdf5"
    verbose: True    
    data:
      name: "1D_Cahn_Hilliard"
      single_file: True
      reduced_resolution: 4
      reduced_resolution_t: 1
      reduced_batch: 1
      initial_step: 1
      test_ratio: 0.1
      seed: 1

    dataloader:
      batch_size: 50
      num_workers: 1
      pin_memory: False

  model:
    name: "DeepONet"
    base_model: "MLP"
    input_size: 256
    act: "tanh"
    in_channels: 1
    out_channels: 1
    query_dim: 2

  training:
    scenario: "1D_Cahn_Hilliard"
    save_name: "1d_Cahn_Hilliard"
    training_type: "single"
    
    if_training: True
    continue_training: False
    model_path: null
    output_dir: "./checkpoint/"
    
    epochs: 500
    save_period: 20
    seed: 1
    
    optimizer:
      name: 'Adam'
      lr: 1.0e-3
      weight_decay: 1.0e-4
    
    scheduler:
      name: "StepLR"
      step_size: 100
      gamma: 0.5