unet_config:
  datapipe:
    source:
      data_dir: "${ONESCIENCE_DATASETS_DIR}/PDENNEval/data/" 
      file_name: "2D_DarcyFlow_beta0.1_Train.hdf5"
    verbose: True    
    data:
      name: "2D_DarcyFlow"
      single_file: True
      reduced_resolution: 1
      reduced_resolution_t: 1
      reduced_batch: 1
      initial_step: 1
      test_ratio: 0.1
      seed: 0 # 数据 shuffle 种子

    dataloader:
      batch_size: 64
      num_workers: 4
      pin_memory: False

  model:
    name: "UNet"
    in_channels: 1
    out_channels: 1
    init_features: 32

  training:
    pde_name: "2D_Darcy_Flow"
    
    # 模式控制
    if_training: True
    continue_training: False
    model_path: null
    output_dir: "./checkpoint/"
    
    # 训练参数
    seed: 0
    training_type: "single" # "single" or "autoregressive"
    pushforward: False      # 仅在 autoregressive 模式下可能用到
    unroll_step: 1          # 仅在 autoregressive 模式下用到
    
    epochs: 500
    save_period: 20 # 原始代码是 1，这里调整为 20 减少 IO，可按需修改
    
    optimizer:
      name: 'Adam'
      lr: 1.0e-3
      weight_decay: 1.0e-4
    
    scheduler:
      name: "StepLR"
      step_size: 100
      gamma: 0.5