unet_config:
  datapipe:
    source:
      data_dir: "YOUR_DATASET_DIR_PATH"
      file_name: "2D_Burgers_Nu0.001.hdf5"
    verbose: True    
    data:
      name: "2D_Burgers"
      single_file: False
      reduced_resolution: 1
      reduced_resolution_t: 1
      reduced_batch: 1
      initial_step: 10
      test_ratio: 0.1
      seed: 0

    dataloader:
      batch_size: 8
      num_workers: 2
      pin_memory: False

  model:
    name: "UNet"
    in_channels: 2
    out_channels: 2
    init_features: 32

  training:
    pde_name: "2D_Burgers"
    
    # 模式控制
    if_training: True
    continue_training: False
    model_path: null
    output_dir: "./checkpoint/"
    
    # 训练参数
    seed: 0
    training_type: "autoregressive"
    pushforward: True
    unroll_step: 20
    
    epochs: 1
    save_period: 1
    
    # 可视化
    tensorboard: True
    log_dir: "./logs/tensorboard/"
    
    optimizer:
      name: 'Adam'
      lr: 1.0e-3
      weight_decay: 1.0e-4
    
    scheduler:
      name: "StepLR"
      step_size: 100
      gamma: 0.5