deeponet_config:
  datapipe:
    source:
      data_dir: "YOUR_DATASET_DIR_PATH"
      file_name: "2D_Black-Scholes-Barenblatt_r0.05_sigma0.4.hdf5"
    verbose: True    
    data:
      name: "2D_Black-Scholes"
      single_file: True
      reduced_resolution: 1
      reduced_resolution_t: 1
      reduced_batch: 1
      initial_step: 1
      test_ratio: 0.1
      seed: 0

    dataloader:
      batch_size: 50
      num_workers: 1
      pin_memory: False

  model:
    name: "DeepONet"
    base_model: "MLP"
    input_size: 128
    act: "tanh"
    in_channels: 1
    out_channels: 1
    query_dim: 3

  training:
    scenario: "2D_Black-Scholes-Barenblatt"
    save_name: "2d_BS_128"
    training_type: "single"
    
    if_training: True
    continue_training: False
    model_path: null
    output_dir: "./checkpoint/"
    
    epochs: 500
    save_period: 10
    seed: 0
    
    optimizer:
      name: 'Adam'
      lr: 1.0e-3
      weight_decay: 1.0e-4
    
    scheduler:
      name: "StepLR"
      step_size: 50
      gamma: 0.5