_target_: onescience.modules.embedding.mattergen_property_embeddings.PropertyEmbedding
name: energy_above_hull
unconditional_embedding_module:
  _target_: onescience.modules.embedding.mattergen_property_embeddings.EmbeddingVector
  hidden_dim: ${lightning_module.diffusion_module.model.hidden_dim}
conditional_embedding_module:
  _target_: model.diffusion.model_utils.NoiseLevelEncoding
  d_model: ${lightning_module.diffusion_module.model.hidden_dim}
scaler:
  _target_: model.common.utils.data_utils.StandardScalerTorch
