uno_config:
  datapipe:
    source:
      data_dir: "${ONESCIENCE_DATASETS_DIR}/PDENNEval/data/" 
      file_name: "2D_DarcyFlow_beta0.1_Train.hdf5"
    verbose: True        
    data:
      name: "2D_DarcyFlow"
      single_file: True
      reduced_resolution: 1
      reduced_resolution_t: 1
      reduced_batch: 1
      initial_step: 1
      test_ratio: 0.1
      seed: 0 # 数据 shuffle 种子

    dataloader:
      batch_size: 64
      num_workers: 4
      pin_memory: False

  model:
    name: "UNO"
    num_channels: 1 # 原配置是 1
    width: 30 # 原配置是 30

  training:
    pde_name: "2D_Darcy_Flow"
    training_type: "single" 
    t_train: 2
    
    if_training: True
    continue_training: False
    model_path: null
    output_dir: "./checkpoint/"
    
    epochs: 500 # 原配置是 50，但可能是笔误，UNet是500，这里保持原样 50 或改为 500
    save_period: 20
    seed: 0
    
    optimizer:
      name: 'Adam'
      lr: 1.0e-3
      weight_decay: 1.0e-4
    
    scheduler:
      name: "StepLR"
      step_size: 100
      gamma: 0.5