name: oc20_ef_4dcu
description: UMA OC20 finetune - 1 node x 4 DCU (energy+forces)
launch:
  launcher: torchrun
  num_nodes: 1
  num_gpus: 4
  omp_num_threads: 1
env:
  conda_env: uv311_mat
  modules:
  - sghpc-mpi-gcc/26.3
slurm:
  partition: hpctest01
  time: '2:00:00'
  cpus_per_task: 64
job:
  device_type: CUDA
  scheduler:
    mode: LOCAL
    ranks_per_node: 4
    num_nodes: 1
  debug: true
  run_dir: ./uma_finetune_runs/
  run_name: oc20_ef_4dcu
  logger: null
max_neighbors: 300
epochs: 1
steps: null
batch_size: 2
lr: 0.0004
weight_decay: 0.001
evaluate_every_n_steps: 100
checkpoint_every_n_steps: null
data:
  dataset_name: oc20
  elem_refs:
  - -9.01836389963216e-17
  - -3.384793156087369
  - -3.552713678800501e-15
  - -1.4210854715202004e-14
  - -3.552713678800501e-15
  - -6.096600969433027
  - -8.288307365078008
  - -8.377401871630358
  - -4.73277382959691
  - -4.218847493575595e-15
  - 8.881784197001252e-15
  - -1.5758719946770752
  - 3.552713678800501e-15
  - -3.605510955946432
  - -5.341968801697664
  - -5.26720503097145
  - -4.566219949129778
  - -3.0961819892844145
  - 0.0
  - -1.5790045471096414
  - -2.4721953289673877
  - -6.6807503507860915
  - -7.74796841292303
  - -8.403945117874883
  - -8.507943997230633
  - -7.859727128191719
  - -7.202700747006435
  - -6.283218856635957
  - -4.8972399918354865
  - -2.9438503901650144
  - -0.6766002592520115
  - -2.577391165910655
  - -4.06962014738207
  - -4.497309369632559
  - -3.780665648345848
  - -5.329070518200751e-15
  - -1.3322676295501878e-15
  - -1.4256648977370752
  - -2.412526481733912
  - -7.014442857905434
  - -8.512272383088028
  - -9.592355889199172
  - -9.910578824883942
  - -9.267018354580234
  - -8.354773494931816
  - -6.854409258193916
  - -4.840002859370445
  - -1.918019107887611
  - -0.23821365616560497
  - -2.0561553805596358
  - -3.3842132848566258
  - -3.667988196267832
  - -3.032988525381068
  - 2.220446049250313e-16
  - 0.0
  - -1.6559264334420458
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - -9.875111813171198
  - -11.052180114376393
  - -11.621851352916064
  - -11.117519848695258
  - -10.219707389902464
  - -8.357987841676932
  - -5.796390731438155
  - -2.701232714681403
  - 0.32034288848399406
  - -1.8259293180072989
  - -2.991135014870159
  - -3.3375851657056166
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  normalizer_rmsd: 0.3184592617813517
  train_dataset:
    splits:
      train:
        src: ${ONESCIENCE_DATASETS_DIR}/data/oc20_finetune/train
    format: ase_db
    transforms:
      common_transform:
        dataset_name: ${data.dataset_name}
      stress_reshape_transform:
        dataset_name: ${data.dataset_name}
  val_dataset:
    splits:
      val:
        src: ${ONESCIENCE_DATASETS_DIR}/data/oc20_finetune/val
    format: ase_db
    transforms:
      common_transform:
        dataset_name: ${data.dataset_name}
      stress_reshape_transform:
        dataset_name: ${data.dataset_name}
  regress_stress: false
  pass_through_head_outputs: true
  heads:
    efs:
      module: onescience.modules.head.uma_head.MLP_EFS_Head
  tasks_list:
  - _target_: onescience.utils.uma.units.mlip_unit.mlip_unit.Task
    name: energy
    level: system
    property: energy
    loss_fn:
      _target_: onescience.modules.loss.uma_loss.DDPMTLoss
      loss_fn:
        _target_: onescience.modules.loss.uma_loss.PerAtomMAELoss
      coefficient: 20
    out_spec:
      dim:
      - 1
      dtype: float32
    normalizer:
      _target_: onescience.utils.uma.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: ${data.normalizer_rmsd}
    element_references:
      _target_: onescience.utils.uma.normalization.element_references.ElementReferences
      element_references:
        _target_: torch.DoubleTensor
        _args_:
        - ${data.elem_refs}
    datasets:
    - ${data.dataset_name}
    metrics:
    - mae
    - per_atom_mae
  - _target_: onescience.utils.uma.units.mlip_unit.mlip_unit.Task
    name: forces
    level: atom
    property: forces
    train_on_free_atoms: true
    eval_on_free_atoms: true
    loss_fn:
      _target_: onescience.modules.loss.uma_loss.DDPMTLoss
      loss_fn:
        _target_: onescience.modules.loss.uma_loss.L2NormLoss
      reduction: mean
      coefficient: 2
    out_spec:
      dim:
      - 3
      dtype: float32
    normalizer:
      _target_: onescience.utils.uma.normalization.normalizer.Normalizer
      mean: 0.0
      rmsd: ${data.normalizer_rmsd}
    datasets:
    - ${data.dataset_name}
    metrics:
    - mae
    - cosine_similarity
    - magnitude_error
train_dataset:
  _target_: onescience.datapipes.materials.custom_stack.storage.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    finetune_dataset: ${data.train_dataset}
  combined_dataset_config:
    sampling:
      type: temperature
      temperature: 1.0
train_dataloader:
  _target_: onescience.datapipes.materials.uma.dataloader_builder.get_dataloader
  dataset: ${train_dataset}
  batch_sampler_fn:
    _target_: onescience.utils.uma.common.data_parallel.BalancedBatchSampler
    _partial_: true
    batch_size: ${batch_size}
    shuffle: true
    seed: 0
  num_workers: 0
  collate_fn:
    _target_: onescience.utils.uma.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${data.tasks_list}
    exclude_keys: []
val_dataset:
  _target_: onescience.datapipes.materials.custom_stack.storage.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    finetune_dataset: ${data.val_dataset}
  combined_dataset_config:
    sampling:
      type: temperature
      temperature: 1.0
eval_dataloader:
  _target_: onescience.datapipes.materials.uma.dataloader_builder.get_dataloader
  dataset: ${val_dataset}
  batch_sampler_fn:
    _target_: onescience.utils.uma.common.data_parallel.BalancedBatchSampler
    _partial_: true
    batch_size: ${batch_size}
    shuffle: false
    seed: 0
  num_workers: 0
  collate_fn:
    _target_: onescience.utils.uma.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${data.tasks_list}
    exclude_keys: []
runner:
  _target_: onescience.utils.uma.components.train.train_runner.TrainEvalRunner
  train_dataloader: ${train_dataloader}
  eval_dataloader: ${eval_dataloader}
  train_eval_unit:
    _target_: onescience.utils.uma.units.mlip_unit.mlip_unit.MLIPTrainEvalUnit
    job_config: ${job}
    tasks: ${data.tasks_list}
    model:
      _target_: onescience.utils.uma.units.mlip_unit.mlip_unit.initialize_finetuning_model
      checkpoint_location: ${ONESCIENCE_MODELS_DIR}/weight/uma-s-1p1_converted.pt
      overrides:
        backbone:
          otf_graph: true
          max_neighbors: ${max_neighbors}
          regress_stress: ${data.regress_stress}
          always_use_pbc: false
        pass_through_head_outputs: ${data.pass_through_head_outputs}
      heads: ${data.heads}
    optimizer_fn:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: ${lr}
      weight_decay: ${weight_decay}
    cosine_lr_scheduler_fn:
      _target_: onescience.utils.uma.units.mlip_unit.mlip_unit._get_consine_lr_scheduler
      _partial_: true
      warmup_factor: 0.2
      warmup_epochs: 0.01
      lr_min_factor: 0.01
      epochs: ${epochs}
      steps: ${steps}
    print_every: 10
    clip_grad_norm: 100
  max_epochs: ${epochs}
  max_steps: ${steps}
  evaluate_every_n_steps: ${evaluate_every_n_steps}
  callbacks:
  - _target_: onescience.utils.uma.components.train.train_runner.TrainCheckpointCallback
    checkpoint_every_n_steps: ${checkpoint_every_n_steps}
    max_saved_checkpoints: 5
  - _target_: torchtnt.framework.callbacks.TQDMProgressBar
