pino_config:
  datapipe:
    source:
      data_dir: "${ONESCIENCE_DATASETS_DIR}/PDENNEval/data/" 
      file_name: "2D_DarcyFlow_beta1.0_Train.hdf5"
    verbose: True    
    data:
      name: "2D_DarcyFlow"
      single_file: True
      reduced_resolution: 2
      reduced_resolution_t: 1
      reduced_resolution_pde: 1
      reduced_resolution_pde_t: 1
      reduced_batch: 1
      initial_step: 1
      test_ratio: 0.1
      if_grid_norm: False
      seed: 0

    dataloader:
      batch_size: 50
      num_workers: 2
      pin_memory: False

  model:
    name: "PINO"
    width: 32
    modes1: [12, 12, 12, 12]
    modes2: [12, 12, 12, 12]
    fc_dim: 128
    act: 'gelu'
    in_channels: 1
    out_channels: 1

  training:
    pde_name: "2D_DarcyFlow"
    training_type: "single"
    
    # Loss Weights for PINO
    ic_loss: 0.0
    f_loss: 1.0
    xy_loss: 10.0
    
    # 模式控制
    if_training: True
    continue_training: False
    model_path: null
    output_dir: "./checkpoint/"
    save_name: "2d_darcy_2x"
    
    epochs: 500
    save_period: 20
    seed: 0
    
    optimizer:
      name: 'Adam'
      lr: 1.0e-3
      weight_decay: 1.0e-4
    
    scheduler:
      name: "StepLR"
      step_size: 100
      gamma: 0.5