resource_ids:
  model: OneScience/esmfold/
  dataset: OneScience/esmfold_dataset

paths:
  sample_fasta: data/sample/few_proteins.fasta
  output_dir: outputs/esmfold_pdb
  model_dir: .
  checkpoint: checkpoints/esmfold_3B_v1.pt

inference:
  num_recycles: null
  max_tokens_per_batch: 1024
  chunk_size: 128
  cpu_only: true
  cpu_offload: false

dataset_expectation:
  dataset_repo_id: OneScience/esmfold_dataset
  expected_dataset_local_path: ../../dataset/bio_esmfold_dataset
  required_weight_files:
    - weight/esmfold_3B_v1.pt
