beno_config:
  datapipe:
    source:
      data_dir: "${ONESCIENCE_BENO_DATA_DIR}/Dirichlet/"
      cache_dir: "./cache_data/"
      file_prefix: "N32_4c"
    verbose: True

    data:
      name: "BENO_Elliptic"
      ntrain: 900
      ntest: 100
      resolution: 32
      ns: 10
      domain_bounds: [[0, 1], [0, 1]]

    dataloader:
      batch_size: 1
      num_workers: 0
      pin_memory: True

  model:
    name: "HeteroGNS"
    nnode_in_features: 10
    nnode_out_features: 1
    nedge_in_features: 7
    nmlp_layers: 2
    act: "relu"
    boundary_dim: 128
    trans_layer: 3
    width: 64
    ker_width: 256

  training:
    output_dir: "./model/"
    save_dir_name: "Resolution_32_poisson"
    epochs: 1000
    save_period: 1
    seed: 2025

    optimizer:
      name: "Adam"
      lr: 1.0e-5
      weight_decay: 5.0e-4

    scheduler:
      name: "CosineAnnealingWarmRestarts"
      T_0: 16
      T_mult: 2
